log_type notice
log_dest stdout

listener 1883
allow_anonymous true
socket_domain ipv4

# Add 0.0.0.0 to listen on all interfaces and not only localhost
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true
socket_domain ipv4 #ipv6 is disable on the stock GOAT kernel, and that causes libwebsocket to fail silently without this