#enum
uint8 MOTOR_CUTTER_UP = 1 #刀片调上
uint8 MOTOR_CUTTER_DOWN = 2 #刀片调下
uint8 MOTOR_CUTTER_DEFAULT = 0 #默认方式，档位调节
uint8 type 
uint8 value  #当type=0 的时候 value 取值1-10
 
---

uint8 MOTOR_CUTTER_SUCESS = 1 
uint8 MOTOR_CUTTER_FAIL = 0
uint8 res
uint8 value #获取时候档位值
